### Insert new post
POST http://localhost:8000/post/insert
Content-Type: application/json

{
  "message": "insert new post", "senderId": "1"
}

### Get a post by id
GET http://localhost:8000/post/6970b0928fc7b2e0c7ef7513

### Get all posts 
GET http://localhost:8000/posts

### Get posts by sender
GET http://localhost:8000/post?senderId=1