### Insert new post
POST http://localhost:8000/post/insert
Content-Type: application/json

{
  "message": "insert new post"
}

### Get a post by id
GET http://localhost:8000/post/6970b0928fc7b2e0c7ef7513
### Get all posts 
GET http://localhost:8000/posts

### Update a post
PUT http://localhost:8000/post/6970b0928fc7b2e0c7ef7513
Content-Type: application/json

{
  "message": "This is the updated message.",
  "sender": "1"
}